api-version: 2024-02-02-preview
location: italynorth
identity:
   type: UserAssigned
   userAssignedIdentities:
    ? " /subscriptions/efd8f007-0923-49a2-959c-fecfdc08c756/resourcegroups/rg-poc-sfera-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mi-aca-poc-sfera-dev"
    : {}
properties:
  environmentId: /subscriptions/efd8f007-0923-49a2-959c-fecfdc08c756/resourceGroups/rg-poc-sfera-dev/providers/Microsoft.App/managedEnvironments/cae-poc-sfera-dev
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: true
      targetPort: 8080
      transport: http
      allowInsecure: true
  template:
    containers:
      - image: acrpocsfera.azurecr.io/helloworld:latest
        name: helloworldyaml
        env:
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: 8080
    scale:
      minReplicas: 1
