# Use the official image as a parent image.
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

# Set the working directory.
WORKDIR /app

# Copy everything into the working directory.
COPY . ./

# Restore the dependencies.
RUN dotnet restore

# Build the application.
RUN dotnet publish -c Release -o out

# Use the runtime image as a parent image.
FROM mcr.microsoft.com/dotnet/aspnet:8.0

# Set the working directory.
WORKDIR /app

# Copy the build output from the build image.
COPY --from=build-env /app/out .

# Expose port 80 for the application.
EXPOSE 8080

# Define the command to start the application.
ENTRYPOINT ["dotnet", "HelloWorld.dll"]