apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-app
  labels:
    app: internal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-app
  template:
    metadata:
      labels:
        app: internal-app
    spec:
      containers:
        - name: api
          image: tsacrcmpdev.azurecr.io/api:latest
          ports:
            - name: http
              containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: internal-app
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: internal-app